/*
 * Mob Head drop settings
 *
 * chance: base chance from 0.0 to 1.0 (0.10 = 10%)
 * lootingBonus: extra chance per Looting level
 *
 * This is the only file that needs editing to rebalance head drops.
 */
export const MOB_HEAD_DROP_CONFIG = Object.freeze({
  "minecraft:allay": { item: "zombie:allay_mask", chance: 0.30, lootingBonus: 0.00 },
  "minecraft:armadillo": { item: "zombie:armadillo_mask", chance: 0.10, lootingBonus: 0.02 },
  "minecraft:axolotl": { resolver: "axolotl", chance: 0.175, lootingBonus: 0.02 },
  "minecraft:bat": { item: "zombie:bat_mask", chance: 0.10, lootingBonus: 0.02 },
  "minecraft:bee": { resolver: "bee", chance: 0.20, lootingBonus: 0.02 },
  "minecraft:blaze": { item: "zombie:blaze_mask", chance: 0.01, lootingBonus: 0.001 },
  "minecraft:bogged": { item: "zombie:bogged_mask", chance: 0.01, lootingBonus: 0.003 },
  "minecraft:breeze": { item: "zombie:breeze_mask", chance: 0.01, lootingBonus: 0.02 },
  "minecraft:camel": { item: "zombie:camel1_mask", chance: 0.30, lootingBonus: 0.10 },
  "minecraft:camel_husk": { item: "zombie:camel_husk_mask", chance: 0.10, lootingBonus: 0.02 },
  "minecraft:cat": { resolver: "cat", chance: 0.33, lootingBonus: 0.02 },
  "minecraft:cave_spider": { item: "zombie:cavespider_mask", chance: 0.05, lootingBonus: 0.01 },
  "minecraft:chicken": { resolver: "chicken", chance: 0.02, lootingBonus: 0.001 },
  "minecraft:cod": { item: "zombie:cod_mask", chance: 0.10, lootingBonus: 0.01 },
  "minecraft:copper_golem": { resolver: "copper_golem", chance: 0.05, lootingBonus: 0.015 },
  "minecraft:cow": { resolver: "cow", chance: 0.01, lootingBonus: 0.001 },
  "minecraft:creaking": { item: "zombie:creaking_mask", chance: 0.20, lootingBonus: 0.01 },
  "minecraft:dolphin": { item: "zombie:dolphin_mask", chance: 0.33, lootingBonus: 0.02 },
  "minecraft:donkey": { item: "zombie:donkey_mask", chance: 0.20, lootingBonus: 0.09 },
  "minecraft:drowned": { item: "zombie:drowned_mask", chance: 0.01, lootingBonus: 0.02 },
  "minecraft:elder_guardian": { item: "zombie:elderguardian_mask", chance: 1.00, lootingBonus: 0.00 },
  "minecraft:enderman": { item: "zombie:enderman_mask", chance: 0.01, lootingBonus: 0.001 },
  "minecraft:endermite": { item: "zombie:endermite_mask", chance: 0.10, lootingBonus: 0.01 },
  "minecraft:evocation_illager": { item: "zombie:illager_mask", chance: 0.015, lootingBonus: 0.02 },
  "minecraft:evoker": { item: "zombie:illager_mask", chance: 0.015, lootingBonus: 0.02 },
  "minecraft:fox": { resolver: "fox", chance: 0.10, lootingBonus: 0.004 },
  "minecraft:frog": { resolver: "frog", chance: 0.10, lootingBonus: 0.004 },
  "minecraft:ghast": { item: "zombie:ghast_mask", chance: 0.063, lootingBonus: 0.013 },
  "minecraft:glow_squid": { item: "zombie:glow_squid_mask", chance: 0.10, lootingBonus: 0.01 },
  "minecraft:goat": { resolver: "goat", chance: 0.10, lootingBonus: 0.01 },
  "minecraft:guardian": { item: "zombie:guardian_mask", chance: 0.01, lootingBonus: 0.001 },
  "minecraft:hoglin": { item: "zombie:hog_mask", chance: 0.03, lootingBonus: 0.02 },
  "minecraft:horse": { resolver: "horse", chance: 0.27, lootingBonus: 0.01 },
  "minecraft:husk": { item: "zombie:husk_mask", chance: 0.06, lootingBonus: 0.01 },
  "minecraft:iron_golem": { item: "zombie:iron_golem_mask", chance: 0.05, lootingBonus: 0.015 },
  "minecraft:llama": { resolver: "llama", chance: 0.24, lootingBonus: 0.02 },
  "minecraft:magma_cube": { item: "zombie:magma_cube_mask", chance: 0.01, lootingBonus: 0.001 },
  "minecraft:mooshroom": { resolver: "mooshroom", chance: 0.10, lootingBonus: 0.001 },
  "minecraft:mule": { item: "zombie:mule_mask", chance: 0.20, lootingBonus: 0.05 },
  "minecraft:nautilus": { item: "zombie:nautilus_mask", chance: 0.10, lootingBonus: 0.01 },
  "minecraft:ocelot": { item: "zombie:ocelot_mask", chance: 0.33, lootingBonus: 0.02 },
  "minecraft:panda": { resolver: "panda", chance: 0.27, lootingBonus: 0.004 },
  "minecraft:parched": { item: "zombie:parched_mask", chance: 0.06, lootingBonus: 0.05 },
  "minecraft:parrot": { resolver: "parrot", chance: 0.25, lootingBonus: 0.02 },
  "minecraft:phantom": { item: "zombie:phantom_mask", chance: 0.10, lootingBonus: 0.01 },
  "minecraft:pig": { resolver: "pig", chance: 0.01, lootingBonus: 0.001 },
  "minecraft:piglin_brute": { item: "zombie:piglin_brute_mask", chance: 0.10, lootingBonus: 0.01 },
  "minecraft:pillager": { item: "zombie:pillager_mask", chance: 0.05, lootingBonus: 0.005 },
  "minecraft:polar_bear": { item: "zombie:polar_bear_mask", chance: 0.20, lootingBonus: 0.05 },
  "minecraft:pufferfish": { item: "zombie:pufferfish_mask", chance: 0.15, lootingBonus: 0.01 },
  "minecraft:rabbit": { resolver: "rabbit", chance: 0.26, lootingBonus: 0.05 },
  "minecraft:ravager": { item: "zombie:ravager_mask", chance: 0.25, lootingBonus: 0.02 },
  "minecraft:salmon": { item: "zombie:salmon_mask", chance: 0.10, lootingBonus: 0.01 },
  "minecraft:sheep": { resolver: "sheep", chance: 0.018, lootingBonus: 0.003 },
  "minecraft:shulker": { resolver: "shulker", chance: 0.05, lootingBonus: 0.01 },
  "minecraft:silverfish": { item: "zombie:siliverfish_mask", chance: 0.05, lootingBonus: 0.01 },
  "minecraft:skeleton_horse": { item: "zombie:skeleton_horse_mask", chance: 0.10, lootingBonus: 0.10 },
  "minecraft:slime": { item: "zombie:slime_mask", chance: 0.01, lootingBonus: 0.001 },
  "minecraft:sniffer": { item: "zombie:sniffer_mask", chance: 0.10, lootingBonus: 0.01 },
  "minecraft:snow_golem": { item: "zombie:snowman_mask", chance: 0.05, lootingBonus: 0.01 },
  "minecraft:spider": { item: "zombie:spider_mask", chance: 0.01, lootingBonus: 0.001 },
  "minecraft:squid": { item: "zombie:squid_mask", chance: 0.05, lootingBonus: 0.01 },
  "minecraft:stray": { item: "zombie:stray_mask", chance: 0.06, lootingBonus: 0.05 },
  "minecraft:strider": { resolver: "strider", chance: 0.10, lootingBonus: 0.05 },
  "minecraft:sulfur_cube": { item: "zombie:sulfur_cube_mask", chance: 0.10, lootingBonus: 0.01 },
  "minecraft:tadpole": { item: "zombie:tadpole_mask", chance: 0.10, lootingBonus: 0.01 },
  "minecraft:tropicalfish": { item: "zombie:tropical_fish_mask", chance: 0.10, lootingBonus: 0.01 },
  "minecraft:tropical_fish": { item: "zombie:tropical_fish_mask", chance: 0.10, lootingBonus: 0.01 },
  "minecraft:turtle": { item: "zombie:turtle_mask", chance: 0.10, lootingBonus: 0.01 },
  "minecraft:vex": { resolver: "vex", chance: 0.10, lootingBonus: 0.01 },
  "minecraft:villager": { resolver: "villager", chance: 0.05, lootingBonus: 0.01 },
  "minecraft:villager_v2": { resolver: "villager", chance: 0.05, lootingBonus: 0.01 },
  "minecraft:vindication_illager": { item: "zombie:vindicator_mask", chance: 0.015, lootingBonus: 0.015 },
  "minecraft:vindicator": { item: "zombie:vindicator_mask", chance: 0.015, lootingBonus: 0.015 },
  "minecraft:wandering_trader": { item: "zombie:wandering_trader_mask", chance: 0.01, lootingBonus: 0.001 },
  "minecraft:warden": { item: "zombie:warden_mask", chance: 1.00, lootingBonus: 0.00 },
  "minecraft:witch": { item: "zombie:witch_mask", chance: 0.01, lootingBonus: 0.001 },
  "minecraft:wither": { resolver: "wither", chance: 1.00, lootingBonus: 0.00 },
  "minecraft:wither_boss": { resolver: "wither", chance: 1.00, lootingBonus: 0.00 },
  "minecraft:wolf": { resolver: "wolf", chance: 0.20, lootingBonus: 0.01 },
  "minecraft:zoglin": { item: "zombie:zoglin_mask", chance: 0.20, lootingBonus: 0.05 },
  "minecraft:zombie_horse": { item: "zombie:zombie_horse_mask", chance: 0.01, lootingBonus: 0.001 },
  "minecraft:zombie_pigman": { item: "zombie:zombie_piglin_mask", chance: 0.01, lootingBonus: 0.001 },
  "minecraft:zombie_nautilus": { resolver: "zombie_nautilus", chance: 0.10, lootingBonus: 0.01 },
  "minecraft:zombified_piglin": { item: "zombie:zombie_piglin_mask", chance: 0.01, lootingBonus: 0.001 },
  "minecraft:zombie_villager": { item: "zombie:zombie_villager_v2_mask", chance: 0.05, lootingBonus: 0.02 },
  "minecraft:zombie_villager_v2": { item: "zombie:zombie_villager_v2_mask", chance: 0.05, lootingBonus: 0.02 }
});

/*
 * Special appearance rolls happen only after the mob successfully drops a head.
 * The Wither values are weights that must total 1.00.
 */
export const SPECIAL_HEAD_VARIANT_CHANCES = Object.freeze({
  striderSuffocated: 0.20,
  vexCharging: 0.20,
  witherNormal: 0.80,
  witherArmored: 0.15,
  witherInvulnerable: 0.03,
  witherArmoredInvulnerable: 0.02
});
